/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import { useState } from "react";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [value, setValue] = useState("");
  const [data, setData] = useState<any[]>([]);
  const handleSubmit = (event: { preventDefault: () => void }) => {
    event.preventDefault();
    fetch(`https://omdbapi.com/?s=${value}&apikey=7249d26b`)
      .then((res) => res.json())
      .then((data) => {
        setData(data.Search);
        console.log(data);
      });
  };

  return (
    <>
      <Head>
        <title>Movie Searcher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>MOVIE SEARCHER</h1>
        <form onSubmit={handleSubmit}>
          <input
            type="text"
            placeholder="Movie name"
            value={value}
            onChange={(e) => setValue(e.target.value)}
          />
          <button type="submit">Search</button>
        </form>
        {data
          ? data.map((movies) => {
              return (
                <div className="movie" key={movies.imdbID}>
                  <Link href={"/details" + "?q=" + movies.imdbID}>
                    Title: {movies.Title}
                  </Link>

                  <h4>Year: {movies.Year}</h4>
                  <img src={movies.Poster} alt="" />
                </div>
              );
            })
          : null}
      </main>
    </>
  );
}
